### ISSUE TITLE
Use build context in docker-compose

### ISSUE THREAD

**Issue by xiaofei-du** [instill-ai/model-backend#28]
Follow [vdp](https://github.com/instill-ai/vdp/blob/main/docker-compose.yml) and use locally built images

```
 model-backend-migrate:
   build:
     context: .
   image: instill/model-backend:dev 
   ...
 model-backend:
   build:
     context: .
   image: instill/model-backend:dev
   ...
```

https://github.com/instill-ai/model-backend/blob/60a5f099607a89c6f3e9c9e9f069837f07d72151/docker-compose.yml#L15-L27
